package ar.edu.utn.frc.tup.piii.engine;

public enum ErrorCode {
    NOT_YOUR_TURN,
    WRONG_PHASE,
    MATCH_NOT_ACTIVE,
    ENERGY_ALREADY_ATTACHED,
    BENCH_FULL,
    INSUFFICIENT_ENERGY,
    CANNOT_ATTACK_FIRST_TURN,
    POKEMON_ASLEEP,
    POKEMON_PARALYZED,
    RETREAT_ALREADY_USED,
    SUPPORTER_ALREADY_PLAYED,
    EVOLVE_NOT_ALLOWED,
    CARD_NOT_IN_HAND,
    INVALID_TARGET,
    KNOCKOUT_REPLACEMENT_REQUIRED,
    TOOL_ALREADY_EQUIPPED,
    UNKNOWN_EFFECT_CODE,
    MISSING_TARGET,
    ABILITY_NOT_FOUND,
    ABILITY_ALREADY_USED,
    POKEMON_CANNOT_USE_ABILITY,
    STADIUM_ALREADY_PLAYED
}
