package ar.edu.utn.frc.tup.piii.engine.action;

public enum GameActionType {
    PUT_BASIC_ON_BENCH,
    ATTACH_ENERGY,
    EVOLVE_POKEMON,
    PLAY_TRAINER,
    RETREAT_ACTIVE,
    DECLARE_ATTACK,
    END_TURN,
    DRAW_CARD,
    TAKE_PRIZE_CARD,
    ATTACH_TOOL,
    USE_ABILITY,
    CHOOSE_KO_REPLACEMENT,
    SETUP_PLACE_ACTIVE,
    SETUP_PLACE_BENCH,
    SETUP_REMOVE_ACTIVE,
    SETUP_REMOVE_BENCH,
    CONFIRM_SETUP,
    RESOLVE_MULLIGAN_DRAW,
    RESOLVE_INITIAL_MULLIGAN
}
