package ar.edu.utn.frc.tup.piii.engine.trainer;

public enum EffectType {
    DRAW_CARDS,
    HEAL,
    SEARCH_BASIC_POKEMON,
    SEARCH_ENERGY,
    EVOLVE_SEARCH,
    DISCARD_AND_DRAW,
    SWITCH_POKEMON,
    SHUFFLE_HAND_INTO_DECK,
    ATTACH_EXTRA_ENERGY,
    DAMAGE_MODIFY,
    CONDITION_REMOVE,
    REVIVE,
    TOOL_ATTACH,
    STADIUM_PLAY,
    EVOLVE_DIRECT,
    LOOK_TOP_SEARCH,
    REVIVE_TO_DECK,
    SEARCH_ENERGY_TO_HAND,
    OPPONENT_SHUFFLE_HAND_DRAW,
    COIN_FLIP_DRAW,
    HEAL_WITH_DISCARD,
    RETURN_POKEMON_TO_DECK,
    DISCARD_OPPONENT_ENERGY
}
